tables:
  'redshift_poc_iceberg.alert_v3':
    schema:
      - action: VARCHAR
      - policy: VARCHAR
      - transaction_id: INTEGER
      - organization_unit: VARCHAR
      - app: VARCHAR
      - instance_id: VARCHAR
      - timestamp: TIMESTAMP
      - url: VARCHAR
      - count: INTEGER
      - ur_normalized: VARCHAR
      - alert_type: VARCHAR
      - ns_tenant_id: INTEGER
      - ns_creation_timestamp: TIMESTAMP
      - signature_id: INTEGER

materializedViews:
  MV_SIMPLE_PROJECTION:
    definition: >
      SELECT ns_tenant_id, alert_type, "action", policy
      FROM "redshift_poc_iceberg"."alert_v3"
    targetTable: poc_mvs.mv_simple_projection

  MV_SIMPLE_AGG:
    definition: >
      SELECT ns_tenant_id, alert_type, SUM("count") AS count
      FROM "redshift_poc_iceberg"."alert_v3"
      GROUP BY ns_tenant_id, alert_type
    targetTable: poc_mvs.mv_simple_agg

  MV_ALERT_EVENT_DAILY_AGG:
    definition: >
      SELECT
        date_trunc('day', timestamp)  AS timestamp,
        action,
        ns_tenant_id,
        alert_type,
        SPLIT(organization_unit, '/') AS OU,
        CONCAT(app, instance_id) AS ns_app_instance,
        SUM("count")   AS count
      FROM
        "redshift_poc_iceberg"."alert_v3"
      GROUP BY
        date_trunc('day', timestamp),
        action,
        ns_tenant_id,
        alert_type,
        SPLIT(organization_unit, '/'),
        CONCAT(app, instance_id)
    targetTable: redshift_poc_iceberg.alert_event_daily_sum

  MV_ALERT_EVENT_DAILY_AGG_DETAILED:
    definition: >
      SELECT
        policy,
        action,
        transaction_id,
        date_trunc('day', timestamp)  AS timestamp,
        ns_tenant_id,
        alert_type,
        SPLIT(organization_unit, '/') AS OU,
        CONCAT(app, instance_id) AS ns_app_instance,
        SUM("count")   AS count
      FROM
        "redshift_poc_iceberg"."alert_v3"
      GROUP BY
        policy,
        action,
        transaction_id,
        date_trunc('day', timestamp),
        ns_tenant_id,
        alert_type,
        SPLIT(organization_unit, '/'),
        CONCAT(app, instance_id)
    targetTable: redshift_poc_iceberg.alert_event_daily_sum_detailed
