tables:
  'redshift_poc_iceberg.alert_v3':
    schema:
      - action: VARCHAR
      - policy: VARCHAR
      - transaction_id: INTEGER
      - organization_unit: VARCHAR
      - app: VARCHAR
      - instance_id: VARCHAR
      - timestamp: TIMESTAMP
      - url: VARCHAR
      - count: INTEGER
      - numbytes: INTEGER
      - file_size: INTEGER
      - ur_normalized: VARCHAR
      - alert_type: VARCHAR
      - malware_name: VARCHAR
      - site: VARCHAR
      - ns_tenant_id: INTEGER
      - ns_creation_timestamp: TIMESTAMP
      - signature_id: INTEGER

  'redshift_poc_iceberg.page_v3':
    schema:
      - organization_unit: VARCHAR
      - appcategory: VARCHAR
      - app: VARCHAR
      - ur_normalized: VARCHAR
      - timestamp: TIMESTAMP
      - ns_tenant_id: INTEGER
      - ns_category_id: INTEGER
      - count: INTEGER
      - site: VARCHAR

  'redshift_poc_iceberg.appcategory':
    schema:
      - ns_tenant_id: INTEGER
      - category_id: INTEGER
      - app_category_current_name: VARCHAR


materializedViews:
  MV_SIMPLE_PROJECTION:
    definition: >
      SELECT ns_tenant_id, alert_type, "action", policy
      FROM "redshift_poc_iceberg"."alert_v3"
    targetTable: poc_mvs.mv_simple_projection

  MV_SIMPLE_AGG:
    definition: >
      SELECT ns_tenant_id, alert_type, SUM("count") AS count
      FROM "redshift_poc_iceberg"."alert_v3"
      GROUP BY ns_tenant_id, alert_type
    targetTable: poc_mvs.mv_simple_agg

  MV_ALERT_EVENT_DAILY_AGG:
    definition: >
      SELECT
        date_trunc('day', timestamp)  AS timestamp,
        action,
        ns_tenant_id,
        alert_type,
        SPLIT(organization_unit, '/') AS OU,
        CONCAT(app, instance_id) AS ns_app_instance,
        SUM("count")   AS count
      FROM
        "redshift_poc_iceberg"."alert_v3"
      GROUP BY
        date_trunc('day', timestamp),
        action,
        ns_tenant_id,
        alert_type,
        SPLIT(organization_unit, '/'),
        CONCAT(app, instance_id)
    targetTable: redshift_poc_iceberg.alert_event_daily_sum

  MV_ALERT_EVENT_DAILY_AGG_DETAILED:
    definition: >
      SELECT
        policy,
        action,
        transaction_id,
        date_trunc('day', timestamp)  AS timestamp,
        ns_tenant_id,
        alert_type,
        organization_unit,
        app,
        instance_id,
        malware_name,
        site,
        SUM("count") AS count,
        SUM(numbytes) AS numbytes,
        SUM(file_size) AS file_size
      FROM
        "redshift_poc_iceberg"."alert_v3"
      GROUP BY
        policy,
        action,
        transaction_id,
        date_trunc('day', timestamp),
        ns_tenant_id,
        alert_type,
        organization_unit,
        app,
        instance_id,
        malware_name,
        site
    targetTable: redshift_poc_iceberg.alert_event_daily_sum_detailed

  MV_PAGE_EVENT_DAILY_AGG_DETAILED:
    definition: >
      SELECT
        date_trunc('day', timestamp)  AS timestamp,
        app,
        ns_tenant_id,
        ns_category_id,
        organization_unit,
        ur_normalized,
        appcategory,
        site,
        SUM("count") AS count,
        SUM(numbytes) AS numbytes,
        SUM(client_bytes) AS client_bytes,
        SUM(server_bytes) AS server_bytes
      FROM
        "redshift_poc_iceberg"."page_v3"
      GROUP BY
        date_trunc('day', timestamp),
        app,
        ns_tenant_id,
        ns_category_id,
        organization_unit,
        ur_normalized,
        appcategory,
        site
    targetTable: redshift_poc_iceberg.page_event_daily_sum
